(package "souls"
         "0.1.0"
         "A Souls-like tutorial game")

(website-url "https://github.com/sltong/emacs-souls")
(keywords "games" "multimedia")

(package-file "souls.el")

(script "test" "test/souls-test.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "cl-lib")
;; (depends-on "gv")
(depends-on "eieio")
;; (depends-on "eieio-base")

;; no linter warning about sentences ending in double spaces
(setq sentence-end-double-space nil)
