(package "souls"
         "0.1.0"
         "A Souls-like tutorial game")

(website-url "https://escritoire.software/emacs-souls")
(keywords "games" "multimedia" "help")

(package-file "souls.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "cl-lib")
;; (depends-on "gv")
(depends-on "eieio")
;; (depends-on "eieio-base")

;; no linter warning about sentences ending in double spaces
(setq sentence-end-double-space nil)
